# Topics Subscribed
OdomTopic:                  '/drone_1/visual_slam/odom'
ImuTopic:                   '/drone_1/sim/imu'
                            # ImuTopic is body acc provided by simulator, with g removed
MapTopic:                   '/random_complex/global_map'
TargetTopic:                '/move_base_simple/goal'
TrajTriggerTopic:           '/traj_start_trigger'

# Topics Advertised
TrajectoryTopic:            '/traj_server/trajectory'
AutoManualTopic:            '/traj_server/auto_manual'
InflateMapTopic:            '/fsto/visualization/inflate_map'

# Frame Names
OdomFrame:                  'odom'

# Params
UnitScaleInSI:               1.0

R3SafeRadius:                0.40   # 控制 RRT 搜索路径与障碍物的安全距离

BodySafeRadius:              0.20

SensingRadius:               4.0    # 局部感知半径 (米)

EdfResolution:               0.10

R3Bound:                     [-10.0, 10.0, -10.0, 10.0, 0.0, 5.0] 
                             # [xmin, xmax, ymin, ymax, zmin, zmax]

SearchDuration:              0.10

TryOut:                      5

MaxAccRate:                  2.00

MaxVelRate:                  4.00

WeightT:                     128.0

WeightAcc:                   0.0

WeightJerk:                  1.0

Iterations:                  23

TemporalResolution:          0.02

SpatialResolution:           0.10

Epsilon:                     0.02

Local_map_update_dt:         0.10   # 10Hz

# Online replanning
Replan_dt:                  1.00   # 周期性重规划间隔
Collision_check_horizon:    2.00   # 检查当前轨迹未来 1.5s 是否发生碰撞
Collision_check_dt:         0.10
Local_goal_ratio:           1.40   # local goal = Local_goal_ratio * sensing radius；该参数大于1时 Collision_check_horizon
Replan_time_ahead:          0.10   # 旧轨迹前向拼接点
Min_traj_remaining_time:    1.50   # 当前轨迹剩余时间不足时强制重规划
Min_replan_interval:        0.50   # 防止过于频繁发布新轨迹
Emergency_stop_duration:    1.00   # 刹停轨迹持续时间
Local_goal_sample_angle:    40.0   # degree 局部目标候选采样角度间隔
Local_goal_speed:           0.5

# 算法选择
Alg:                         3      # 2 - 时域缩放； 3 - 精细化局部约束处理

# Flight mode
# 1: click goal mode
# 2: preset waypoint mode
Flight_mode:                 2

Waypoint_reach_thresh:       0.50

# x1, y1, z1, x2, y2, z2, ...
Preset_waypoints:            [
                              -9.0, 0.0, 2.0,
                               0.0, 9.0, 3.0,
                               9.0, -1.0, 2.0,
                               1.0, -9.0, 2.0
                             ]